// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *MenuLevel2 → Sub Menu Contents*
 */
export interface MenuLevel2DocumentDataSubMenuContentsItem {
  /**
   * Sub Menu field in *MenuLevel2 → Sub Menu Contents*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: MenuLevel2.SubMenuContents[].SubMenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  SubMenu: prismic.ContentRelationshipField<"SubMenuContent">;

  /**
   * Sub Menu Collection Link field in *MenuLevel2 → Sub Menu Contents*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: collection link
   * - **API ID Path**: MenuLevel2.SubMenuContents[].sub_menu_collection_link
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  sub_menu_collection_link: prismic.IntegrationField;
}

/**
 * Content for MenuLevel2 documents
 */
interface MenuLevel2DocumentData {
  /**
   * Menu Title field in *MenuLevel2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: MenuLevel2.MenuTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  MenuTitle: prismic.KeyTextField;

  /**
   * Menu Link field in *MenuLevel2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: MenuLevel2.MenuLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  MenuLink: prismic.LinkField;

  /**
   * Collection Link field in *MenuLevel2*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: collection link
   * - **API ID Path**: MenuLevel2.collection_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection_link: prismic.IntegrationField;

  /**
   * Sub Menu Contents field in *MenuLevel2*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: MenuLevel2.SubMenuContents[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  SubMenuContents: prismic.GroupField<
    Simplify<MenuLevel2DocumentDataSubMenuContentsItem>
  >;
}

/**
 * MenuLevel2 document from Prismic
 *
 * - **API ID**: `MenuLevel2`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuLevel2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MenuLevel2DocumentData>,
    "MenuLevel2",
    Lang
  >;

type NavigationListDocumentDataSlicesSlice = MenuNavigationItemSlice;

/**
 * Content for NavigationList documents
 */
interface NavigationListDocumentData {
  /**
   * Slice Zone field in *NavigationList*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: NavigationList.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationListDocumentDataSlicesSlice>;
}

/**
 * NavigationList document from Prismic
 *
 * - **API ID**: `NavigationList`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationListDocumentData>,
    "NavigationList",
    Lang
  >;

type SubMenuContentDocumentDataSlicesSlice =
  | MenuNavigationItemSlice
  | MenuFeatureBlogSlice
  | MenuFeatureProductSlice
  | MenuFeaturePromotionSlice;

/**
 * Content for Sub Menu Content documents
 */
interface SubMenuContentDocumentData {
  /**
   * MenuTitle field in *Sub Menu Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: SubMenuContent.menutitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menutitle: prismic.KeyTextField;

  /**
   * Menu Link field in *Sub Menu Content*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: SubMenuContent.MenuLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  MenuLink: prismic.LinkField;

  /**
   * Link to Collection field in *Sub Menu Content*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Collection Link
   * - **API ID Path**: SubMenuContent.link_to_collection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  link_to_collection: prismic.IntegrationField;

  /**
   * colour field in *Sub Menu Content*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: SubMenuContent.colour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  colour: prismic.ColorField;

  /**
   * products field in *Sub Menu Content*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: SubMenuContent.products
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  products: prismic.IntegrationField;

  /**
   * MenuLayer field in *Sub Menu Content*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: SubMenuContent.menulayer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  menulayer: prismic.BooleanField;

  /**
   * LinkOnlyDesktop field in *Sub Menu Content*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: SubMenuContent.linkonly
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  linkonly: prismic.BooleanField;

  /**
   * linkOnlyMobile field in *Sub Menu Content*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: SubMenuContent.linkonlymobile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  linkonlymobile: prismic.BooleanField;

  /**
   * Slice Zone field in *Sub Menu Content*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: SubMenuContent.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuContentDocumentDataSlicesSlice>;
}

/**
 * Sub Menu Content document from Prismic
 *
 * - **API ID**: `SubMenuContent`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubMenuContentDocumentData>,
    "SubMenuContent",
    Lang
  >;

/**
 * Item in *TopMenuLevel → Sub Menu Contents*
 */
export interface TopMenuLevelDocumentDataSubMenuContentsItem {
  /**
   * hidenz field in *TopMenuLevel → Sub Menu Contents*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: TopMenuLevel.SubMenuContents[].hidenz
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;

  /**
   * Sub Menu field in *TopMenuLevel → Sub Menu Contents*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: TopMenuLevel.SubMenuContents[].SubMenu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  SubMenu: prismic.ContentRelationshipField<"SubMenuContent" | "MenuLevel2">;

  /**
   * Collection Link field in *TopMenuLevel → Sub Menu Contents*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select a Collection
   * - **API ID Path**: TopMenuLevel.SubMenuContents[].collection_link
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection_link: prismic.IntegrationField;
}

/**
 * Content for TopMenuLevel documents
 */
interface TopMenuLevelDocumentData {
  /**
   * Sub Menu Contents field in *TopMenuLevel*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: TopMenuLevel.SubMenuContents[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  SubMenuContents: prismic.GroupField<
    Simplify<TopMenuLevelDocumentDataSubMenuContentsItem>
  >;
}

/**
 * TopMenuLevel document from Prismic
 *
 * - **API ID**: `TopMenuLevel`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopMenuLevelDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TopMenuLevelDocumentData>,
    "TopMenuLevel",
    Lang
  >;

/**
 * Item in *Banner Management → banners*
 */
export interface BannerManagementDocumentDataBannersItem {
  /**
   * Banner field in *Banner Management → banners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<"Mobile">;

  /**
   * Link field in *Banner Management → banners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Tile Banner field in *Banner Management → banners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_banner: prismic.ImageField<"mobile">;

  /**
   * Tile Banner URL field in *Banner Management → banners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_banner_url: prismic.LinkField;

  /**
   * Tile Banner 1 field in *Banner Management → banners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_banner1: prismic.ImageField<"mobile">;

  /**
   * Tile Banner URL 1 field in *Banner Management → banners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner_url1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_banner_url1: prismic.LinkField;

  /**
   * Tile Banner 2 field in *Banner Management → banners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_banner2: prismic.ImageField<"mobile">;

  /**
   * Tile Banner URL 2 field in *Banner Management → banners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].tile_banner_url2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_banner_url2: prismic.LinkField;

  /**
   * Start Date field in *Banner Management → banners*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Banner Management → banners*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Collection 1 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection1
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection1: prismic.IntegrationField;

  /**
   * Collection 2 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection2
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection2: prismic.IntegrationField;

  /**
   * Collection 3 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection3
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection3: prismic.IntegrationField;

  /**
   * Collection 4 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection4
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection4: prismic.IntegrationField;

  /**
   * Collection 5 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection5
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection5: prismic.IntegrationField;

  /**
   * Collection 6 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection6
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection6: prismic.IntegrationField;

  /**
   * Collection 7 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection7
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection7: prismic.IntegrationField;

  /**
   * Collection 8 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection8
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection8: prismic.IntegrationField;

  /**
   * Collection 9 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection9
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection9: prismic.IntegrationField;

  /**
   * Collection 10 field in *Banner Management → banners*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[].collection10
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection10: prismic.IntegrationField;

  /**
   * hidenz field in *Banner Management → banners*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner_management.banners[].hidenz
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;

  /**
   * site field in *Banner Management → banners*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ALL
   * - **API ID Path**: banner_management.banners[].site
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  site: prismic.SelectField<"ALL" | "AU" | "NZ", "filled">;
}

/**
 * Content for Banner Management documents
 */
interface BannerManagementDocumentData {
  /**
   * banners field in *Banner Management*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.banners[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  banners: prismic.GroupField<
    Simplify<BannerManagementDocumentDataBannersItem>
  >;
}

/**
 * Banner Management document from Prismic
 *
 * - **API ID**: `banner_management`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerManagementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BannerManagementDocumentData>,
    "banner_management",
    Lang
  >;

/**
 * Content for BlogAuthor documents
 */
interface BlogauthorDocumentData {
  /**
   * Name field in *BlogAuthor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogauthor.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Picture field in *BlogAuthor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogauthor.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * BlogAuthor document from Prismic
 *
 * - **API ID**: `blogauthor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogauthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogauthorDocumentData>,
    "blogauthor",
    Lang
  >;

/**
 * Item in *BlogPost → RelatedProducts*
 */
export interface BlogpostDocumentDataRelatedproductsItem {
  /**
   * RelatedProduct field in *BlogPost → RelatedProducts*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.relatedproducts[].relatedproduct
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  relatedproduct: prismic.IntegrationField;
}

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * Title field in *BlogPost*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Article Image field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.article_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  article_image: prismic.ImageField<never>;

  /**
   * Author field in *BlogPost*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"blogauthor">;

  /**
   * Category field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * RelatedProducts field in *BlogPost*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.relatedproducts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  relatedproducts: prismic.GroupField<
    Simplify<BlogpostDocumentDataRelatedproductsItem>
  >;

  /**
   * Created At field in *BlogPost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.created_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  created_at: prismic.DateField;

  /**
   * Tags field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.tags
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tags: prismic.KeyTextField;

  /**
   * Body Html field in *BlogPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.body_html
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_html: prismic.RichTextField;

  /**
   * Meta Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type BrandtestDocumentDataSlicesSlice = BrandNavigationListsSlice;

/**
 * Content for BrandMenuData documents
 */
interface BrandtestDocumentData {
  /**
   * Slice Zone field in *BrandMenuData*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: brandtest.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BrandtestDocumentDataSlicesSlice>;
}

/**
 * BrandMenuData document from Prismic
 *
 * - **API ID**: `brandtest`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandtestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BrandtestDocumentData>,
    "brandtest",
    Lang
  >;

/**
 * Item in *Category → Left Menu*
 */
export interface CategoryDocumentDataLeftMenuItem {
  /**
   * Left Menu Image field in *Category → Left Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.left_menu[].sub_category_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sub_category_image: prismic.ImageField<never>;

  /**
   * Left Collection field in *Category → Left Menu*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: category.left_menu[].left_collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  left_collection: prismic.IntegrationField;

  /**
   * Left Menu Link field in *Category → Left Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category.left_menu[].left_menu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  left_menu_link: prismic.LinkField;

  /**
   * Left Menu Title field in *Category → Left Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.left_menu[].left_menu_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  left_menu_title: prismic.KeyTextField;
}

/**
 * Item in *Category → FAQs*
 */
export interface CategoryDocumentDataFaqsItem {
  /**
   * Collection Question field in *Category → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.faqs[].collection_question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collection_question: prismic.KeyTextField;

  /**
   * Collections Answer field in *Category → FAQs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.faqs[].collections_answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collections_answer: prismic.KeyTextField;
}

/**
 * Item in *Category → Brands*
 */
export interface CategoryDocumentDataBrandsItem {
  /**
   * Brand Logo field in *Category → Brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.brands[].brand_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  brand_logo: prismic.ImageField<never>;

  /**
   * Brand Collection field in *Category → Brands*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: category.brands[].brand_collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  brand_collection: prismic.IntegrationField;

  /**
   * Brand Link field in *Category → Brands*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category.brands[].brand_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand_link: prismic.LinkField;
}

/**
 * Item in *Category → Internal Links*
 */
export interface CategoryDocumentDataInternalLinksItem {
  /**
   * Link Title field in *Category → Internal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.internal_links[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link Collection field in *Category → Internal Links*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: category.internal_links[].link_collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  link_collection: prismic.IntegrationField;

  /**
   * Link for Link field in *Category → Internal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category.internal_links[].link_for_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_for_link: prismic.LinkField;
}

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Real Collection field in *Category*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: category.real_collection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  real_collection: prismic.IntegrationField;

  /**
   * Parent Category field in *Category*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: category.parent_category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent_category: prismic.ContentRelationshipField<"category">;

  /**
   * Is IA ON? field in *Category*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: category.ia_is_on
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  ia_is_on: prismic.BooleanField;

  /**
   * Link field in *Category*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Left Menu field in *Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.left_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  left_menu: prismic.GroupField<Simplify<CategoryDocumentDataLeftMenuItem>>;

  /**
   * Banner field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<"Mobile">;

  /**
   * Tile Banner field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.tile_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tile_banner: prismic.ImageField<"mobile">;

  /**
   * Tile Banner Link field in *Category*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: category.tile_banner_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tile_banner_link: prismic.LinkField;

  /**
   * Description field in *Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * FAQs field in *Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.faqs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  faqs: prismic.GroupField<Simplify<CategoryDocumentDataFaqsItem>>;

  /**
   * Brands field in *Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.brands[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brands: prismic.GroupField<Simplify<CategoryDocumentDataBrandsItem>>;

  /**
   * Internal Links field in *Category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.internal_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  internal_links: prismic.GroupField<
    Simplify<CategoryDocumentDataInternalLinksItem>
  >;

  /**
   * Tagalys Widget ID field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.tagalys_widget_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagalys_widget_id: prismic.KeyTextField;

  /**
   * Show Description On Top field in *Category*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: category.show_description_on_top
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_description_on_top: prismic.BooleanField;

  /**
   * hidenz field in *Category*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: category.hidenz
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Gift Guide → firstBanner*
 */
export interface GiftGuideDocumentDataFirstBannerItem {
  /**
   * image field in *Gift Guide → firstBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.firstBanner[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * imageMobile field in *Gift Guide → firstBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.firstBanner[].imageMobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageMobile: prismic.ImageField<never>;

  /**
   * link field in *Gift Guide → firstBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.firstBanner[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Gift Guide → secondBanner*
 */
export interface GiftGuideDocumentDataSecondBannerItem {
  /**
   * image field in *Gift Guide → secondBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.secondBanner[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * imageMobile field in *Gift Guide → secondBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.secondBanner[].imageMobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageMobile: prismic.ImageField<never>;

  /**
   * link field in *Gift Guide → secondBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.secondBanner[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type GiftGuideDocumentDataSlicesSlice = ShopByCategorySlice | ShopByPriceSlice;

/**
 * Content for Gift Guide documents
 */
interface GiftGuideDocumentData {
  /**
   * firstBanner field in *Gift Guide*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.firstBanner[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  firstBanner: prismic.GroupField<
    Simplify<GiftGuideDocumentDataFirstBannerItem>
  >;

  /**
   * secondBanner field in *Gift Guide*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.secondBanner[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  secondBanner: prismic.GroupField<
    Simplify<GiftGuideDocumentDataSecondBannerItem>
  >;

  /**
   * Slice Zone field in *Gift Guide*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gift_guide.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GiftGuideDocumentDataSlicesSlice>;
}

/**
 * Gift Guide document from Prismic
 *
 * - **API ID**: `gift_guide`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GiftGuideDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GiftGuideDocumentData>,
    "gift_guide",
    Lang
  >;

/**
 * Item in *HairWeekPage → Promo Definition*
 */
export interface HairweekpageDocumentDataPromoDefinitionItem {
  /**
   * Start Date field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * Title field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Desc field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].desc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  desc: prismic.KeyTextField;

  /**
   * Product one field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].product_one
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product_one: prismic.IntegrationField;

  /**
   * Product two field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].product_two
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product_two: prismic.IntegrationField;

  /**
   * Product Three field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].product_three
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product_three: prismic.IntegrationField;

  /**
   * Product Four field in *HairWeekPage → Promo Definition*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[].product_four
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  product_four: prismic.IntegrationField;
}

/**
 * Content for HairWeekPage documents
 */
interface HairweekpageDocumentData {
  /**
   * Promo Definition field in *HairWeekPage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hairweekpage.promo_definition[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  promo_definition: prismic.GroupField<
    Simplify<HairweekpageDocumentDataPromoDefinitionItem>
  >;
}

/**
 * HairWeekPage document from Prismic
 *
 * - **API ID**: `hairweekpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HairweekpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HairweekpageDocumentData>,
    "hairweekpage",
    Lang
  >;

/**
 * Item in *Home Page → HeroBanner*
 */
export interface HomePageDocumentDataHerobannerItem {
  /**
   * SlideImg field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.herobanner[].slideimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slideimg: prismic.ImageField<"mobile">;

  /**
   * hidenz field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home_page.herobanner[].hidenz
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;

  /**
   * SlideLink field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.herobanner[].slidelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  slidelink: prismic.LinkField;

  /**
   * LinkedProduct field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.herobanner[].linkedproduct
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  linkedproduct: prismic.IntegrationField;

  /**
   * Collection field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select collection
   * - **API ID Path**: home_page.herobanner[].collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection: prismic.IntegrationField;

  /**
   * site field in *Home Page → HeroBanner*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ALL
   * - **API ID Path**: home_page.herobanner[].site
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  site: prismic.SelectField<"ALL" | "AU" | "NZ", "filled">;
}

type HomePageDocumentDataSlicesSlice =
  | ShopByCategorySlice
  | BestSellersSlice
  | GiftGuideSlice
  | ShopByHairTypeSlice
  | JustForYouSlice
  | BrandSlice
  | CurrentPromotionsSlice;

/**
 * Item in *Home Page → blog*
 */
export interface HomePageDocumentDataBlogItem {
  /**
   * heading field in *Home Page → blog*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.blog[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * excerpt field in *Home Page → blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.blog[].excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * image field in *Home Page → blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.blog[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkField;

  /**
   * link field in *Home Page → blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.blog[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Home Page → Featured Blog Posts*
 */
export interface HomePageDocumentDataFeaturedBlogPostsItem {
  /**
   * Feature Blog Post field in *Home Page → Featured Blog Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.featured_blog_posts[].feature_blog_post
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  feature_blog_post: prismic.ContentRelationshipField<"blogpost">;
}

/**
 * Item in *Home Page → Meta Tags*
 */
export interface HomePageDocumentDataMetaTagsItem {
  /**
   * Name field in *Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_tags[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Content field in *Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_tags[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Property field in *Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_tags[].property
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property: prismic.KeyTextField;
}

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * HeroBanner field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.herobanner[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  herobanner: prismic.GroupField<Simplify<HomePageDocumentDataHerobannerItem>>;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * blog field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.blog[]
   * - **Tab**: Blog Section
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  blog: prismic.GroupField<Simplify<HomePageDocumentDataBlogItem>>;

  /**
   * Featured Blog Posts field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.featured_blog_posts[]
   * - **Tab**: Blog Section
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_blog_posts: prismic.GroupField<
    Simplify<HomePageDocumentDataFeaturedBlogPostsItem>
  > /**
   * Tab Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.tab_title
   * - **Tab**: Meta Tags
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  tab_title: prismic.KeyTextField;

  /**
   * Meta Tags field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_tags[]
   * - **Tab**: Meta Tags
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  meta_tags: prismic.GroupField<Simplify<HomePageDocumentDataMetaTagsItem>>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Location → Opening Hours*
 */
export interface LocationDocumentDataOpeningHoursItem {
  /**
   * Day Of The Week field in *Location → Opening Hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.openingHours[].weekDay
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  weekDay: prismic.KeyTextField;

  /**
   * openTime field in *Location → Opening Hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.openingHours[].openTime
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  openTime: prismic.KeyTextField;

  /**
   * closeTime field in *Location → Opening Hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.openingHours[].closeTime
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  closeTime: prismic.KeyTextField;
}

/**
 * Item in *Location → images*
 */
export interface LocationDocumentDataImagesItem {
  /**
   * image field in *Location → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Location → indicators*
 */
export interface LocationDocumentDataIndicatorsItem {
  /**
   * name field in *Location → indicators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.indicators[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

type LocationDocumentDataSlicesSlice = never;

/**
 * Content for Location documents
 */
interface LocationDocumentData {
  /**
   * name field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * address field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * description field in *Location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * coordinate field in *Location*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.coordinate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  coordinate: prismic.GeoPointField;

  /**
   * phone field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * direction field in *Location*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: location.direction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  direction: prismic.LinkField;

  /**
   * Iframe Booking field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.iframe_booking
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iframe_booking: prismic.KeyTextField;

  /**
   * Call for Booking field in *Location*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: location.call_for_booking
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  call_for_booking: prismic.BooleanField;

  /**
   * Opening Hours field in *Location*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.openingHours[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  openingHours: prismic.GroupField<
    Simplify<LocationDocumentDataOpeningHoursItem>
  >;

  /**
   * images field in *Location*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<LocationDocumentDataImagesItem>>;

  /**
   * indicators field in *Location*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.indicators[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  indicators: prismic.GroupField<Simplify<LocationDocumentDataIndicatorsItem>>;

  /**
   * Meta Title field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.metaTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaTitle: prismic.KeyTextField;

  /**
   * Meta Description field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.metaDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Slice Zone field in *Location*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: location.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LocationDocumentDataSlicesSlice>;
}

/**
 * Location document from Prismic
 *
 * - **API ID**: `location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LocationDocumentData>,
    "location",
    Lang
  >;

/**
 * Item in *LongTail → Pages*
 */
export interface LongtailDocumentDataPagesItem {
  /**
   * Keyword field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].keyword
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;

  /**
   * URL field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Subtype field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].subtype
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtype: prismic.KeyTextField;

  /**
   * TagsSearchPage field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].tagsSearchPage
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagsSearchPage: prismic.KeyTextField;

  /**
   * MetaTitle field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].metaTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaTitle: prismic.KeyTextField;

  /**
   * H1 field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * MetaDescription field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].metaDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * BodyCopy field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].bodyCopy
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bodyCopy: prismic.KeyTextField;

  /**
   * CategorySlug field in *LongTail → Pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[].categorySlug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  categorySlug: prismic.KeyTextField;
}

/**
 * Content for LongTail documents
 */
interface LongtailDocumentData {
  /**
   * Pages field in *LongTail*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: longtail.pages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pages: prismic.GroupField<Simplify<LongtailDocumentDataPagesItem>>;
}

/**
 * LongTail document from Prismic
 *
 * - **API ID**: `longtail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LongtailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LongtailDocumentData>,
    "longtail",
    Lang
  >;

/**
 * Item in *Main Layout → Top Left Menu*
 */
export interface MainLayoutDocumentDataTopLeftMenuItem {
  /**
   * Link Name field in *Main Layout → Top Left Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopLeftMenu[].LinkName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  LinkName: prismic.KeyTextField;

  /**
   * Link field in *Main Layout → Top Left Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopLeftMenu[].Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Link: prismic.LinkField;

  /**
   * Collection Link Left field in *Main Layout → Top Left Menu*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select Collection
   * - **API ID Path**: main-layout.TopLeftMenu[].collection_link_left
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection_link_left: prismic.IntegrationField;

  /**
   * site field in *Main Layout → Top Left Menu*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ALL
   * - **API ID Path**: main-layout.TopLeftMenu[].site
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  site: prismic.SelectField<"ALL" | "AU" | "NZ", "filled">;
}

/**
 * Item in *Main Layout → Top Right Menu*
 */
export interface MainLayoutDocumentDataTopRightMenuItem {
  /**
   * Link Name field in *Main Layout → Top Right Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopRightMenu[].LinkName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  LinkName: prismic.KeyTextField;

  /**
   * Link field in *Main Layout → Top Right Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopRightMenu[].Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Link: prismic.LinkField;

  /**
   * Collection Link Right field in *Main Layout → Top Right Menu*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select Collection
   * - **API ID Path**: main-layout.TopRightMenu[].collection_link_right
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection_link_right: prismic.IntegrationField;

  /**
   * site field in *Main Layout → Top Right Menu*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ALL
   * - **API ID Path**: main-layout.TopRightMenu[].site
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  site: prismic.SelectField<"ALL" | "AU" | "NZ", "filled">;
}

/**
 * Item in *Main Layout → Help And Support Links*
 */
export interface MainLayoutDocumentDataHelpAndSupportLinksItem {
  /**
   * Link Name field in *Main Layout → Help And Support Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.HelpAndSupportLinks[].LinkName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  LinkName: prismic.KeyTextField;

  /**
   * Link field in *Main Layout → Help And Support Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.HelpAndSupportLinks[].Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Link: prismic.LinkField;
}

/**
 * Item in *Main Layout → Site Info Links*
 */
export interface MainLayoutDocumentDataSiteInfoLinksItem {
  /**
   * Link Name field in *Main Layout → Site Info Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.SiteInfoLinks[].LinkName
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  LinkName: prismic.KeyTextField;

  /**
   * Link field in *Main Layout → Site Info Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.SiteInfoLinks[].Link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  Link: prismic.LinkField;
}

/**
 * Content for Main Layout documents
 */
interface MainLayoutDocumentData {
  /**
   * Offer start-time field in *Main Layout*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.offer_start_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  offer_start_time: prismic.TimestampField;

  /**
   * Offer end-time field in *Main Layout*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.offer_end_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  offer_end_time: prismic.TimestampField;

  /**
   * Timer title of product field in *Main Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.timer_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  timer_title: prismic.KeyTextField /**
   * Top Promo field in *Main Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopPromo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  TopPromo: prismic.KeyTextField;

  /**
   * Top Promo CTA field in *Main Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.top_promo_cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_promo_cta: prismic.KeyTextField;

  /**
   * Top Promo Link field in *Main Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.top_promo_link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  top_promo_link: prismic.LinkField;

  /**
   * Top Promo V2 field in *Main Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.top_promo_v2
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_promo_v2: prismic.RichTextField;

  /**
   * Top Promo V2 NZ field in *Main Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.top_promo_v2_nz
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_promo_v2_nz: prismic.RichTextField;

  /**
   * Phone Number field in *Main Layout*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.PhoneNumber
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  PhoneNumber: prismic.NumberField;

  /**
   * Top Left Menu field in *Main Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopLeftMenu[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  TopLeftMenu: prismic.GroupField<
    Simplify<MainLayoutDocumentDataTopLeftMenuItem>
  >;

  /**
   * Top Right Menu field in *Main Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.TopRightMenu[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  TopRightMenu: prismic.GroupField<
    Simplify<MainLayoutDocumentDataTopRightMenuItem>
  >;

  /**
   * Extradata field in *Main Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.extradata
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  extradata: prismic.KeyTextField /**
   * Help And Support Links field in *Main Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.HelpAndSupportLinks[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  HelpAndSupportLinks: prismic.GroupField<
    Simplify<MainLayoutDocumentDataHelpAndSupportLinksItem>
  >;

  /**
   * Site Info Links field in *Main Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main-layout.SiteInfoLinks[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  SiteInfoLinks: prismic.GroupField<
    Simplify<MainLayoutDocumentDataSiteInfoLinksItem>
  >;
}

/**
 * Main Layout document from Prismic
 *
 * - **API ID**: `main-layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainLayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainLayoutDocumentData>,
    "main-layout",
    Lang
  >;

interface MenuRowDocumentData {}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menuRow`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuRowDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MenuRowDocumentData>,
    "menuRow",
    Lang
  >;

/**
 * Item in *Old Home Page → HeroBanner*
 */
export interface OldHomePageDocumentDataHerobannerItem {
  /**
   * SlideImg field in *Old Home Page → HeroBanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.herobanner[].slideimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slideimg: prismic.ImageField<"mobile">;

  /**
   * SlideLink field in *Old Home Page → HeroBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.herobanner[].slidelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  slidelink: prismic.LinkField;

  /**
   * LinkedProduct field in *Old Home Page → HeroBanner*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.herobanner[].linkedproduct
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  linkedproduct: prismic.IntegrationField;

  /**
   * Collection field in *Old Home Page → HeroBanner*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select collection
   * - **API ID Path**: old_home_page.herobanner[].collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection: prismic.IntegrationField;
}

/**
 * Item in *Old Home Page → brands*
 */
export interface OldHomePageDocumentDataBrandsItem {
  /**
   * Logo field in *Old Home Page → brands*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brands[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * brand link field in *Old Home Page → brands*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brands[].brand-link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "brand-link": prismic.LinkField;

  /**
   * Brand Collection Link field in *Old Home Page → brands*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Choose a collection
   * - **API ID Path**: old_home_page.brands[].brand_collection_link
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  brand_collection_link: prismic.IntegrationField;
}

/**
 * Item in *Old Home Page → blog*
 */
export interface OldHomePageDocumentDataBlogItem {
  /**
   * heading field in *Old Home Page → blog*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.blog[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * excerpt field in *Old Home Page → blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.blog[].excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * image field in *Old Home Page → blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.blog[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkField;

  /**
   * link field in *Old Home Page → blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.blog[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Old Home Page → Featured Blog Posts*
 */
export interface OldHomePageDocumentDataFeaturedBlogPostsItem {
  /**
   * Feature Blog Post field in *Old Home Page → Featured Blog Posts*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.featured_blog_posts[].feature_blog_post
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  feature_blog_post: prismic.ContentRelationshipField<"blogpost">;
}

/**
 * Item in *Old Home Page → Product Recommender*
 */
export interface OldHomePageDocumentDataProductRecommenderItem {
  /**
   * Tab Name field in *Old Home Page → Product Recommender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.product_recommender[].tab_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tab_name: prismic.KeyTextField;

  /**
   * Collection Id field in *Old Home Page → Product Recommender*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.product_recommender[].collection_id
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  collection_id: prismic.NumberField;

  /**
   * Recommender Collection field in *Old Home Page → Product Recommender*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select Collection
   * - **API ID Path**: old_home_page.product_recommender[].recommender_collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  recommender_collection: prismic.IntegrationField;

  /**
   * Is Emarsys API Enabled field in *Old Home Page → Product Recommender*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: old_home_page.product_recommender[].is_emarsys_api_enabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_emarsys_api_enabled: prismic.BooleanField;

  /**
   * Emarsys Logic Name field in *Old Home Page → Product Recommender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.product_recommender[].emarsys_logic_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emarsys_logic_name: prismic.KeyTextField;
}

/**
 * Item in *Old Home Page → Promotions*
 */
export interface OldHomePageDocumentDataPromotionsItem {
  /**
   * heading field in *Old Home Page → Promotions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.promotions[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Old Home Page → Promotions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.promotions[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *Old Home Page → Promotions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.promotions[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkField;

  /**
   * Path field in *Old Home Page → Promotions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.promotions[].path
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  path: prismic.LinkField;

  /**
   * Promotion Collection Link field in *Old Home Page → Promotions*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Choose Collection
   * - **API ID Path**: old_home_page.promotions[].promotion_collection_link
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  promotion_collection_link: prismic.IntegrationField;
}

/**
 * Item in *Old Home Page → Meta Tags*
 */
export interface OldHomePageDocumentDataMetaTagsItem {
  /**
   * Name field in *Old Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.meta_tags[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Content field in *Old Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.meta_tags[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Property field in *Old Home Page → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.meta_tags[].property
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property: prismic.KeyTextField;
}

/**
 * Content for Old Home Page documents
 */
interface OldHomePageDocumentData {
  /**
   * Banner field in *Old Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner: prismic.KeyTextField;

  /**
   * HeroBanner field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.herobanner[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  herobanner: prismic.GroupField<
    Simplify<OldHomePageDocumentDataHerobannerItem>
  > /**
   * Brand heading field in *Old Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brand_heading
   * - **Tab**: Brand
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  brand_heading: prismic.KeyTextField;

  /**
   * Brand description field in *Old Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brand_description
   * - **Tab**: Brand
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  brand_description: prismic.KeyTextField;

  /**
   * Brand cta field in *Old Home Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brand_cta
   * - **Tab**: Brand
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  brand_cta: prismic.LinkField;

  /**
   * CollectionLink field in *Old Home Page*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Choose a collection
   * - **API ID Path**: old_home_page.collectionlink
   * - **Tab**: Brand
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collectionlink: prismic.IntegrationField;

  /**
   * brands field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.brands[]
   * - **Tab**: Brand
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brands: prismic.GroupField<Simplify<OldHomePageDocumentDataBrandsItem>> /**
   * blog field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.blog[]
   * - **Tab**: Blog Section
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  blog: prismic.GroupField<Simplify<OldHomePageDocumentDataBlogItem>>;

  /**
   * Featured Blog Posts field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.featured_blog_posts[]
   * - **Tab**: Blog Section
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_blog_posts: prismic.GroupField<
    Simplify<OldHomePageDocumentDataFeaturedBlogPostsItem>
  > /**
   * Product Recommender field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.product_recommender[]
   * - **Tab**: Product Recommender
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  product_recommender: prismic.GroupField<
    Simplify<OldHomePageDocumentDataProductRecommenderItem>
  > /**
   * Promotions field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.promotions[]
   * - **Tab**: Current Promotions
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  promotions: prismic.GroupField<
    Simplify<OldHomePageDocumentDataPromotionsItem>
  > /**
   * Tab Title field in *Old Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.tab_title
   * - **Tab**: Meta Tags
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  tab_title: prismic.KeyTextField;

  /**
   * Meta Tags field in *Old Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: old_home_page.meta_tags[]
   * - **Tab**: Meta Tags
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  meta_tags: prismic.GroupField<Simplify<OldHomePageDocumentDataMetaTagsItem>>;
}

/**
 * Old Home Page document from Prismic
 *
 * - **API ID**: `old_home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OldHomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OldHomePageDocumentData>,
    "old_home_page",
    Lang
  >;

/**
 * Item in *Promotion Page → Promotion*
 */
export interface PromotionPageDocumentDataPromotionItem {
  /**
   * Promo Banner field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].promo_banner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  promo_banner: prismic.ImageField<"mobile">;

  /**
   * Promo Name field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].promo_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  promo_name: prismic.KeyTextField;

  /**
   * Promo Collection Handle field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].promo_collection_handle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  promo_collection_handle: prismic.KeyTextField;

  /**
   * Promo Collection field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select Collection
   * - **API ID Path**: promotion_page.promotion[].promo_collection
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  promo_collection: prismic.IntegrationField;

  /**
   * Promo Category field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].promo_category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  promo_category: prismic.KeyTextField;

  /**
   * Button Text field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Bg Color field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].button_bg_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_bg_color: prismic.ColorField;

  /**
   * Button Text Color field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].button_text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_text_color: prismic.ColorField;

  /**
   * Related Promo Product 1 field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].related_promo_product_1
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  related_promo_product_1: prismic.IntegrationField;

  /**
   * Related Promo Product 2 field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].related_promo_product_2
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  related_promo_product_2: prismic.IntegrationField;

  /**
   * Related Promo Product 3 field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--ozhairandbeauty`)
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].related_promo_product_3
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  related_promo_product_3: prismic.IntegrationField;

  /**
   * test_blog field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[].test_blog
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  test_blog: prismic.ContentRelationshipField<"blogpost">;

  /**
   * hidenz field in *Promotion Page → Promotion*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotion_page.promotion[].hidenz
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;
}

/**
 * Content for Promotion Page documents
 */
interface PromotionPageDocumentData {
  /**
   * Main Banner field in *Promotion Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.main_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_banner: prismic.ImageField<"mobile">;

  /**
   * Collection Handle field in *Promotion Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.collection_handle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collection_handle: prismic.KeyTextField;

  /**
   * Collection field in *Promotion Page*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: Select Collection
   * - **API ID Path**: promotion_page.collection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  collection: prismic.IntegrationField;

  /**
   * hidenz field in *Promotion Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotion_page.hidenz
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hidenz: prismic.BooleanField;

  /**
   * Promotion field in *Promotion Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_page.promotion[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  promotion: prismic.GroupField<
    Simplify<PromotionPageDocumentDataPromotionItem>
  >;
}

/**
 * Promotion Page document from Prismic
 *
 * - **API ID**: `promotion_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PromotionPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PromotionPageDocumentData>,
    "promotion_page",
    Lang
  >;

type SalonserviceDocumentDataSlicesSlice = HairServiceSlice;

/**
 * Content for Salon Service documents
 */
interface SalonserviceDocumentData {
  /**
   * name field in *Salon Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: salonservice.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * description field in *Salon Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: salonservice.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * serviceType field in *Salon Service*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: salonservice.serviceType
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  serviceType: prismic.SelectField<"hair" | "skin">;

  /**
   * Slice Zone field in *Salon Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: salonservice.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SalonserviceDocumentDataSlicesSlice>;
}

/**
 * Salon Service document from Prismic
 *
 * - **API ID**: `salonservice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SalonserviceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SalonserviceDocumentData>,
    "salonservice",
    Lang
  >;

/**
 * Item in *Search Results Page → Popular Category*
 */
export interface SearchResultsPageDocumentDataPopularCategoryItem {
  /**
   * image field in *Search Results Page → Popular Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search_results_page.popular_category[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Search Results Page → Popular Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search_results_page.popular_category[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Category Link field in *Search Results Page → Popular Category*
   *
   * - **Field Type**: Integration Fields (Catalog: `ozhairandbeauty--collectionstest`)
   * - **Placeholder**: *None*
   * - **API ID Path**: search_results_page.popular_category[].category_link
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  category_link: prismic.IntegrationField;
}

/**
 * Content for Search Results Page documents
 */
interface SearchResultsPageDocumentData {
  /**
   * Popular Category field in *Search Results Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: search_results_page.popular_category[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  popular_category: prismic.GroupField<
    Simplify<SearchResultsPageDocumentDataPopularCategoryItem>
  >;
}

/**
 * Search Results Page document from Prismic
 *
 * - **API ID**: `search_results_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchResultsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchResultsPageDocumentData>,
    "search_results_page",
    Lang
  >;

/**
 * Item in *Variant Swatches → Swatch*
 */
export interface VariantSwatchesDocumentDataSwatchItem {
  /**
   * Colour Name field in *Variant Swatches → Swatch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variant_swatches.swatch[].colour_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  colour_name: prismic.KeyTextField;

  /**
   * Colour Hex field in *Variant Swatches → Swatch*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: variant_swatches.swatch[].colour_hex
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  colour_hex: prismic.ColorField;

  /**
   * Colour Image field in *Variant Swatches → Swatch*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variant_swatches.swatch[].colour_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  colour_image: prismic.ImageField<never>;

  /**
   * Variant SKU field in *Variant Swatches → Swatch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variant_swatches.swatch[].variant_sku
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  variant_sku: prismic.KeyTextField;
}

/**
 * Content for Variant Swatches documents
 */
interface VariantSwatchesDocumentData {
  /**
   * Swatch field in *Variant Swatches*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variant_swatches.swatch[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  swatch: prismic.GroupField<Simplify<VariantSwatchesDocumentDataSwatchItem>>;
}

/**
 * Variant Swatches document from Prismic
 *
 * - **API ID**: `variant_swatches`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VariantSwatchesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VariantSwatchesDocumentData>,
    "variant_swatches",
    Lang
  >;

export type AllDocumentTypes =
  | MenuLevel2Document
  | NavigationListDocument
  | SubMenuContentDocument
  | TopMenuLevelDocument
  | BannerManagementDocument
  | BlogauthorDocument
  | BlogpostDocument
  | BrandtestDocument
  | CategoryDocument
  | GiftGuideDocument
  | HairweekpageDocument
  | HomePageDocument
  | LocationDocument
  | LongtailDocument
  | MainLayoutDocument
  | MenuRowDocument
  | OldHomePageDocument
  | PromotionPageDocument
  | SalonserviceDocument
  | SearchResultsPageDocument
  | VariantSwatchesDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MenuLevel2Document,
      MenuLevel2DocumentData,
      MenuLevel2DocumentDataSubMenuContentsItem,
      NavigationListDocument,
      NavigationListDocumentData,
      NavigationListDocumentDataSlicesSlice,
      SubMenuContentDocument,
      SubMenuContentDocumentData,
      SubMenuContentDocumentDataSlicesSlice,
      TopMenuLevelDocument,
      TopMenuLevelDocumentData,
      TopMenuLevelDocumentDataSubMenuContentsItem,
      BannerManagementDocument,
      BannerManagementDocumentData,
      BannerManagementDocumentDataBannersItem,
      BlogauthorDocument,
      BlogauthorDocumentData,
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataRelatedproductsItem,
      BrandtestDocument,
      BrandtestDocumentData,
      BrandtestDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      CategoryDocumentDataLeftMenuItem,
      CategoryDocumentDataFaqsItem,
      CategoryDocumentDataBrandsItem,
      CategoryDocumentDataInternalLinksItem,
      GiftGuideDocument,
      GiftGuideDocumentData,
      GiftGuideDocumentDataFirstBannerItem,
      GiftGuideDocumentDataSecondBannerItem,
      GiftGuideDocumentDataSlicesSlice,
      HairweekpageDocument,
      HairweekpageDocumentData,
      HairweekpageDocumentDataPromoDefinitionItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataHerobannerItem,
      HomePageDocumentDataSlicesSlice,
      HomePageDocumentDataBlogItem,
      HomePageDocumentDataFeaturedBlogPostsItem,
      HomePageDocumentDataMetaTagsItem,
      LocationDocument,
      LocationDocumentData,
      LocationDocumentDataOpeningHoursItem,
      LocationDocumentDataImagesItem,
      LocationDocumentDataIndicatorsItem,
      LocationDocumentDataSlicesSlice,
      LongtailDocument,
      LongtailDocumentData,
      LongtailDocumentDataPagesItem,
      MainLayoutDocument,
      MainLayoutDocumentData,
      MainLayoutDocumentDataTopLeftMenuItem,
      MainLayoutDocumentDataTopRightMenuItem,
      MainLayoutDocumentDataHelpAndSupportLinksItem,
      MainLayoutDocumentDataSiteInfoLinksItem,
      MenuRowDocument,
      MenuRowDocumentData,
      OldHomePageDocument,
      OldHomePageDocumentData,
      OldHomePageDocumentDataHerobannerItem,
      OldHomePageDocumentDataBrandsItem,
      OldHomePageDocumentDataBlogItem,
      OldHomePageDocumentDataFeaturedBlogPostsItem,
      OldHomePageDocumentDataProductRecommenderItem,
      OldHomePageDocumentDataPromotionsItem,
      OldHomePageDocumentDataMetaTagsItem,
      PromotionPageDocument,
      PromotionPageDocumentData,
      PromotionPageDocumentDataPromotionItem,
      SalonserviceDocument,
      SalonserviceDocumentData,
      SalonserviceDocumentDataSlicesSlice,
      SearchResultsPageDocument,
      SearchResultsPageDocumentData,
      SearchResultsPageDocumentDataPopularCategoryItem,
      VariantSwatchesDocument,
      VariantSwatchesDocumentData,
      VariantSwatchesDocumentDataSwatchItem,
      AllDocumentTypes,
    };
  }
}
