import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* <Script
        src="https://storage.googleapis.com/tagalys-front-end-components/tagalys-api-connector-1.3.2.min.js"
        type="text/javascript"
        strategy="beforeInteractive"
      /> */}
    </html>
  );
}
