import { createClient } from "@/prismicio";
import type { Metadata } from "next";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  }
) {
  const header = await headers();
  const client = createClient()
  const { data: homepageData } = await client.getSingle('home_page', {
    fetch: 'home_page.meta_tags, home_page.tab_title',
  })

  const country = header.get("x-vercel-ip-country");
  const region = header.get("x-vercel-ip-country-region");

  return (
    <html lang="en">
      <body>
        {children}

        <div>
          <div>{country}</div>
        </div>
        <div>{region}</div>
      </body>
      {/* <Script
        src="https://storage.googleapis.com/tagalys-front-end-components/tagalys-api-connector-1.3.2.min.js"
        type="text/javascript"
        strategy="beforeInteractive"
      /> */}
    </html>
  );
}
