import ShopifyAnalytics from "@/components/ShopifyAnalytics";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <p>aaaaaaaaaaaaaaaaa</p>
        <p>bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb</p>
        {children}
        <ShopifyAnalytics/>
      </body>
    </html>
  );
}
